# Generated by Django 4.0.4 on 2022-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0008_infonoun_created_date_infonoun_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('noun_types', models.CharField(choices=[('shaxs', 'Shaxs otlar'), ('narsa', 'Narsa otlar'), ('orin_joy', "O'rin-joy otlar"), ('faoliyat', 'Faoliyat-otlari')], default='shaxs', max_length=15)),
                ('noun_types_structure', models.CharField(choices=[('sodda', 'Sodda'), ('qoshma', "Qo'shma"), ('juft', 'Juft'), ('takroriy', 'Takroriy')], default='sodda', max_length=15)),
                ('noun_making', models.CharField(choices=[('morfologik', 'Morfologik usul'), ('sintaktik', 'Sintaktik usul')], default='morfologik', max_length=15)),
                ('review', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('antonym', models.ManyToManyField(blank=True, related_name='qwe', to='mainapp.antonym')),
                ('hyperonym', models.ManyToManyField(blank=True, related_name='qwerty', to='mainapp.hyperonym')),
                ('hyponym', models.ManyToManyField(blank=True, related_name='qwer', to='mainapp.hyponym')),
                ('synonym', models.ManyToManyField(blank=True, related_name='qw', to='mainapp.synonym')),
            ],
        ),
    ]
