# Generated by Django 4.0.4 on 2022-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouns', '0002_alter_infonoun_noun_making_alter_infonoun_noun_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonoun',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name="So'z"),
        ),
    ]
