# Generated by Django 4.0.4 on 2022-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouns', '0003_alter_infonoun_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonoun',
            name='review',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
