# Generated by Django 4.0.4 on 2022-05-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_infoadjective_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadjective',
            name='antonym',
            field=models.ManyToManyField(blank=True, related_name='antonyms', to='mainapp.antonym'),
        ),
        migrations.AlterField(
            model_name='infoadjective',
            name='hyperonym',
            field=models.ManyToManyField(blank=True, related_name='hyperonyms', to='mainapp.hyperonym'),
        ),
        migrations.AlterField(
            model_name='infoadjective',
            name='hyponym',
            field=models.ManyToManyField(blank=True, related_name='hyponyms', to='mainapp.hyponym'),
        ),
        migrations.AlterField(
            model_name='infoadjective',
            name='synonym',
            field=models.ManyToManyField(blank=True, related_name='synonyms', to='mainapp.synonym'),
        ),
    ]
