# Generated by Django 4.0.4 on 2022-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_infoadjective_antonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadjective',
            name='review',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
