# Generated by Django 4.0.4 on 2022-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_infoadjective_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antonym',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hyperonym',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hyponym',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
