# Generated by Django 4.0.4 on 2022-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_antonym_word_alter_hyperonym_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadjective',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='infoadjective',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
