# Generated by Django 4.0.4 on 2022-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_infoadjective_hyperonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadjective',
            name='adjective_level',
            field=models.CharField(choices=[('oddiy', 'Oddiy daraja'), ('orttirma', 'Orttirma daraja'), ('ozaytirma', 'Ozaytirma daraja'), ('qiyosiy', 'Qiyosiy daraja')], default='oddiy', max_length=15, verbose_name='Sifat darajasi'),
        ),
    ]
