# Generated by Django 4.0.4 on 2022-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_infoadjective_adjective_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadjective',
            name='adjective_type',
            field=models.CharField(choices=[('xususiyat', 'Xususiyat bildiruvchi sifat'), ('rang_tus', 'Rang – tus bildiruvchi sifat'), ('maza_tam', 'Maza – ta’m bildiruvchi sifat'), ('hajm_olchov', 'Hajm – o’lchov bildiruvchi sifat'), ('hid', 'Hid bildiruvchi sifat'), ('makon_zamon', 'Makon-zamon bildiruvchi sifat')], default='xususiyat', max_length=15, verbose_name='Sifat turi'),
        ),
    ]
