# Generated by Django 4.0.4 on 2022-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_infoadjective_adjective_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadjective',
            name='adjective_type_structure',
            field=models.CharField(choices=[('sodda_tub', 'Sodda tub'), ('sodda_yasama', 'Sodda yasama'), ('qoshma', "Qo'shma sifat"), ('juft', 'Juft sifat'), ('takroriy', 'Takroriy sifat')], default='sodda_tub', max_length=15, verbose_name='Tuzilish jihatdan turi'),
        ),
    ]
